---
title: "436_inclass_7_2"
output: html_document
date: "2024-03-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
temperature <- read_csv("https://go.wisc.edu/bo9m94") # Read temperature data into data frame
```

<p> a. Make a version of Figure 2.3 using a line mark (geom_line). Make at least one customization of the theme to make the plot more similar to the version in Figure 2.3. Hint: To group the lines by city, use the group = aesthetic mapping. </p>
```{r}


ggplot(temperature) + # Declare the data frame that we're graphing
  geom_line(aes(x = date, y = temperature, group = city, color = city), size = 1) + # Generate line mark by different cities' temperatures on different dates
  scale_color_manual(values = c("#009E73", "#56B4E9", "#E69F00", "#FF92A5")) + # Use colors similar as Figure 2.3
  theme_minimal() + # Replace the grey background to white background
  theme(
    panel.grid.major = element_line(color = "grey80"),
    panel.grid.minor = element_blank(),
  ) + # Adjust grids style to match Figure 2.3
  scale_x_date(date_labels = "%b") + # Adjust x-axis scale into showing the first three letters of each month
  labs(
    x = "Month",
    y = "Temperature (°F)",
  ) # Write x-axis and y-axis label

```
