---
title: "Stat 436 Homework-4"
author: "Peiyuan Li"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
    highlight: tango
    fig_width: 6
    fig_height: 4
    df_print: paged
  pdf_document:
    toc: true
---
```{r setup}
# Set global chunk options to suppress warnings and messages for a cleaner output
knitr::opts_chunk$set(warnings = FALSE, message = FALSE)

# Load necessary libraries for data manipulation, visualization, and modeling
library(dplyr)
library(tidyverse)
library(ggplot2)
library(tidymodels)
library(broom)
library(tidytext)
```

```{r}
#2. Create Function to preprocess datasets by separating 'year' column
preprocess_dataset <- function(data) {
  filtered_data <- data %>% separate(year, sep = "/", into = "year", convert = TRUE, extra = "drop")
  return(filtered_data)
}
```



```{r}
#3. Data Preprocess
source_of_fund <- preprocess_dataset(read_csv("https://raw.githubusercontent.com/pli233/Working/main/Stat436/Group%20Project/data/source_of_fund.csv"))
#3.2 field_of_study
field_of_study <- preprocess_dataset(read_csv("https://raw.githubusercontent.com/pli233/Working/main/Stat436/Group%20Project/data/field_of_study.csv"))

#3.3 map_data
origin <- preprocess_dataset(read_csv("https://raw.githubusercontent.com/pli233/Working/main/Stat436/Group%20Project/data/origin.csv"))


#3.3 map_data
academic_detail <- preprocess_dataset(read_csv("https://raw.githubusercontent.com/pli233/Working/main/Stat436/Group%20Project/data/academic_detail.csv"))
```


```{r}
academic_detail

# Create a grouped bar chart with custom hover text
plot <- academic_detail %>%
  group_by(year, academic_level) %>%
  summarise(total_students = sum(students), .groups = 'drop') %>%
  mutate(hover_text = paste("Year: ", year, 
                            "<br>Academic Level: ", academic_level, 
                            "<br>Students: ", total_students)) %>%
  plot_ly(x = ~year, y = ~total_students, type = 'bar', color = ~academic_level,
          colors = RColorBrewer::brewer.pal(8, "Set2"),
          text = ~hover_text, hoverinfo = "text") %>%
  layout(yaxis = list(title = 'Number of Students'),
         barmode = 'stack',
         xaxis = list(title = 'Year'),
         title = 'Students Distribution by Academic Level Over Years')

# Display the plot
plot
```